defaults:
  - data: audioset
  - optimizer: adamW
  - trainer: default_trainer
  - patching: frame

model: GRAM-T
model_size: base
save_dir: /projects/0/prjs1338
use_mwmae_decoder : True
# ckpt_path : /gpfs/work4/0/prjs1338/saved_models_naturalistic_mixing/InChannels=2/Fraction=1.0/CleanDataFraction=0.75/Model=GRAM-T/ModelSize=base/LR=0.0002/BatchSize=96/NrSamples=16/Patching=frame/MaskPatch=160/InputL=200/Cluster=False/step=325000.ckpt
seed: 42
